[project]
name = "hgrow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.3",
    "rich>=14.0.0",
    "scholarly>=1.7.11",
]
